[tool.poetry]
name = "robot-code-2025"
version = "0.1.0"
description = ""
authors = [
  "Ishaan Sen <ishaan.sen100@gmail.com", 
  "Omkar Subramaniam <omnikar5@gmail.com>",
  "Aneesha Guna <aneesha.guna@gmail.com>",
  "Matthew Carr <matthewjumpingdolphin@gmail.com>",
  "Dillon Gutowski <dillongutowski@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
robotpy = {extras = ["commands2", "phoenix6", "rev", "navx"], version = "^2025.1.1.1"}
pycowsay = "^0.0.0.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
ruff = "^0.9.0"
python-lsp-server = "^1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
